export { default as auth} from './auth'
export { default as home} from './home'
export { default as user } from './user'

export { default as letter          } from './letters'
export { default as word            } from './words'
export { default as coordinates     } from './coordinates'
export { default as similarLetters  } from './similar-letters'
export { default as saveData        } from './save-data'
export { default as Syllables       } from './syllables'
export { default as SoundLetters    } from './sound-letters'
export { default as Courses         } from './courses'
export { default as InitialData } from './initial-data'
export { default as Combinations    } from './combinations'
export { default as UserProgress    } from './user-progress'

export { default as Menu           } from './data/menu'
export { default as Target         } from './data/target'
export { default as Game           } from './data/game'
export { default as GuessLetter    } from './data/guess-letter'
export { default as DrawLetter     } from './data/draw-letter'
export { default as CompleteWord   } from './data/complete-word'
export { default as FindLetter     } from './data/find-letter'
export { default as SelectWords    } from './data/select-words'
export { default as SelectImages   } from './data/select-images'
export { default as IdentifyLetter } from './data/identify-letter'
